const db = require('quick.db')
const discord = require('discord.js')
const randomstring = require("randomstring");


module.exports = {
    config:{
    name: "code",
    cooldown: 60,
    description: "code",
    },
    async run(bot, message, args) {
        let user = message.author
        const LOCATIONS = [
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),
            randomstring.generate(7),

        ];

        let chosenLocations = LOCATIONS[Math.floor(Math.random() * LOCATIONS.length)]

        const RANDOM_NUMBER = Math.floor(Math.random() * (1000 - 100 + 1)) + 100;

        const FILTER = (m) => {
            return chosenLocations.toLowerCase() === m.content.toLowerCase()
        };

        const COLLECTOR = message.channel.createMessageCollector(FILTER, {
            max: 1,
            time: 12000
        });

        COLLECTOR.on("collect", async (m) => {
            const EMBED = new discord.MessageEmbed()
                .setColor('ff0000')
                .setTitle(`${message.author.username} typed the code first!`)
                .setDescription(`they got \`${RANDOM_NUMBER.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")}\` 💵`)

            db.add(`money_${user.id}`, RANDOM_NUMBER)

            message.channel.send(EMBED);
        });

        COLLECTOR.on("end", (collected) => {
            if (collected.size == 0) {
                return message.channel.send(`:x: **ended**\nnobody typed the code in time`);
            }
        });

        message.channel.send(`**your code is below**\nfirst to type the code in this channel wins \`${RANDOM_NUMBER.toString().replace(/\B(?=(\d{3})+(?!\d))/g,",")}\` 💵\n:x: **NO CHEAETING**\n\`\`\`yaml\n|   |   |   |   |   |${chosenLocations}|   |   |   |   |   |\`\`\``);
    },
};